apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: andromeda
version: 0.1.0
dependencies:
  - name: postgresql
    condition: postgresql.enabled
    repository: file://../../common/postgresql
    version: 0.3.0
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.8.0
  - name: nats
    repository: file://../../common/nats
    version: 0.18.2
  - name: utils
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.12.1
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
  - condition: mysql_metrics.enabled
    name: mysql_metrics
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.7
